# Generated by Django 5.1.6 on 2025-03-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ostrich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostriches', to='ostrich.family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='ostrich.pitch'),
        ),
    ]
