# Generated by Django 5.1.6 on 2025-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Family_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
