# Generated by Django 5.1.6 on 2025-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0002_family_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostrich',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ostrich',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True),
        ),
    ]
