# Generated by Django 5.1.6 on 2025-03-11 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0003_ostrich_age_ostrich_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_check_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg_code', models.CharField(max_length=50, unique=True)),
                ('lay_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fertile', models.CharField(choices=[('Waiting First Check', 'Waiting First Check'), ('Fertile', 'Fertile'), ('Not Fertile', 'Not Fertile')], default='Waiting First Check', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eggs', to='ostrich.batch')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eggs_fathered', to='ostrich.ostrich')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eggs_laid', to='ostrich.ostrich')),
            ],
        ),
    ]
