# Generated by Django 5.1.6 on 2025-03-13 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0005_foodinventory_foodpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('pitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chicks', to='ostrich.pitch')),
            ],
        ),
    ]
