# Generated by Django 5.1.6 on 2025-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0006_chick'),
    ]

    operations = [
        migrations.AddField(
            model_name='chick',
            name='initial_age_in_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
