# Generated by Django 5.1.6 on 2025-03-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0012_chick_status_egg_status_ostrich_status_delete_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chick',
            name='status',
        ),
    ]
