# Generated by Django 5.1.6 on 2025-03-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0013_remove_chick_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chick',
            name='status',
            field=models.CharField(choices=[('exists', 'exists'), ('sold', 'sold')], default='exists', max_length=100, null=True),
        ),
    ]
