# Generated by Django 5.1.6 on 2025-03-15 01:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0016_remove_sale_item_name_sale_chick_sale_egg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OstrichSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('ostrich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrich.ostrich')),
            ],
        ),
    ]
