# Generated by Django 5.1.6 on 2025-03-15 02:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0017_ostrichsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('chick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrich.chick')),
            ],
        ),
        migrations.CreateModel(
            name='EggSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrich.egg')),
            ],
        ),
    ]
